services:
    kafka:
        image: apache/kafka:latest
        container_name: kafka
        ports: 
            - "9092:9092"
    kafka-ui:
        image: provectuslabs/kafka-ui
        container_name: kafka-ui
        ports:
            - "8081:8080"
        environment:
            - DYNAMIC_CONFIG_ENABLED=true
        volumes:
            - ./kafka-ui-socat/kafka-ui-config/:/home/kafkaui/kafka-ui-config
