version: '3.8'

networks:
  kafka-net:
    driver: bridge

services:
  kafka1:
    image: apache/kafka:latest
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - ./props/kafka-cluster-common.env
      - ./props/kafka-cluster-node-1.env
    volumes:
      - ./kafka1/data:/var/lib/kafka/data
      - ./kafka1/logs:/tmp/kraft-combined-logs
    networks:
      - kafka-net

  kafka2:
    image: apache/kafka:latest
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9094:9092"
      - "9095:9093"
    env_file:
      - ./props/kafka-cluster-common.env
      - ./props/kafka-cluster-node-2.env
    volumes:
      - ./kafka2/data:/var/lib/kafka/data
      - ./kafka2/logs:/tmp/kraft-combined-logs
    networks:
      - kafka-net

  kafka3:
    image: apache/kafka:latest
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9096:9092"
      - "9097:9093"
    env_file:
      - ./props/kafka-cluster-common.env
      - ./props/kafka-cluster-node-3.env
    volumes:
      - ./kafka3/data:/var/lib/kafka/data
      - ./kafka3/logs:/tmp/kraft-combined-logs
    networks:
      - kafka-net